/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ses;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CheckNeighboursInGrid {
    public static Iterable<Integer> getSameNeighboursIds(List<Integer> grid, int width, int height, int indexToCheck){

        List<Integer> result = new ArrayList<>();
        List<Integer> neighbours = new ArrayList<>();
        neighbours.add(indexToCheck-width-1);  
        neighbours.add(indexToCheck-width);   
        neighbours.add(indexToCheck-width+1);  
        neighbours.add(indexToCheck-1);     
        neighbours.add(indexToCheck+1);        
        neighbours.add(indexToCheck+width-1); 
        neighbours.add(indexToCheck+width);  
        neighbours.add(indexToCheck+width+1);

        if (indexToCheck >= 0 && indexToCheck <= grid.size()) {
            if((width*height) == grid.size()) {
                for (int i=0; i<neighbours.size(); i++) {
                int neighbourIndex = neighbours.get(i);
                
                    if(neighbourIndex < grid.size()) {
                        if(grid.get(neighbourIndex) == grid.get(indexToCheck)) {
                            result.add(neighbourIndex);
                        }
                    }
                }
            } else {
                throw new IllegalArgumentException("/ Illegal Argument");
            }

        } else {
            throw new IndexOutOfBoundsException("/ Index out of bound");
        }
        return result;
    }

    public static void main(String[] args) {
        List<Integer> grid = Arrays.asList(
            0, 0, 1, 0,
            1, 1, 0, 2,
            2, 0, 1, 3,
            0, 1, 1, 1
        );

        Iterable<Integer> result = CheckNeighboursInGrid.getSameNeighboursIds(grid, 4, 4, 5);
    
        System.out.println("Neighbours: ");
        System.out.println(result);
    }
}
