name: Testen

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle build
        working-directory: ./dependency-management/checkneighbours
        run: ./gradlew build
        
      - name: Run specific test
        working-directory: ./dependency-management/checkneighbours
        run: ./gradlew test --tests "be.ses.CheckNeighboursInGridTest"